// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"questionnaire/internal/biz"
	"questionnaire/internal/conf"
	"questionnaire/internal/data"
	"questionnaire/internal/server"
	"questionnaire/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	questionnaireRepo := data.NewQuestionnaireRepo(dataData, logger)
	questionRepo := data.NewQuestionRepo(dataData,logger)
	questionnaireUsecase := biz.NewQuestionnaireUsecase(questionnaireRepo, logger)
	questionUsecase := biz.NewQuestionUsecase(questionRepo, logger)
	answerRepo := data.NewAnswerRepo(dataData,logger)
	answerUsecase := biz.NewAnswerUsecase(answerRepo,logger)
	questionnaireService := service.NewQuestionnaireService(questionnaireUsecase, questionUsecase,answerUsecase)
	grpcServer := server.NewGRPCServer(confServer, questionnaireService, logger)
	httpServer := server.NewHTTPServer(confServer, questionnaireService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
