// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"questionnaire/ent/question"
	"questionnaire/ent/questionnaire"
	"questionnaire/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionnaireCreate is the builder for creating a Questionnaire entity.
type QuestionnaireCreate struct {
	config
	mutation *QuestionnaireMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (qc *QuestionnaireCreate) SetCreatedAt(t time.Time) *QuestionnaireCreate {
	qc.mutation.SetCreatedAt(t)
	return qc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (qc *QuestionnaireCreate) SetNillableCreatedAt(t *time.Time) *QuestionnaireCreate {
	if t != nil {
		qc.SetCreatedAt(*t)
	}
	return qc
}

// SetUpdatedAt sets the "updated_at" field.
func (qc *QuestionnaireCreate) SetUpdatedAt(t time.Time) *QuestionnaireCreate {
	qc.mutation.SetUpdatedAt(t)
	return qc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (qc *QuestionnaireCreate) SetNillableUpdatedAt(t *time.Time) *QuestionnaireCreate {
	if t != nil {
		qc.SetUpdatedAt(*t)
	}
	return qc
}

// SetName sets the "name" field.
func (qc *QuestionnaireCreate) SetName(s string) *QuestionnaireCreate {
	qc.mutation.SetName(s)
	return qc
}

// SetDescription sets the "description" field.
func (qc *QuestionnaireCreate) SetDescription(s string) *QuestionnaireCreate {
	qc.mutation.SetDescription(s)
	return qc
}

// SetObject sets the "object" field.
func (qc *QuestionnaireCreate) SetObject(s string) *QuestionnaireCreate {
	qc.mutation.SetObject(s)
	return qc
}

// SetAnonymous sets the "anonymous" field.
func (qc *QuestionnaireCreate) SetAnonymous(i int) *QuestionnaireCreate {
	qc.mutation.SetAnonymous(i)
	return qc
}

// SetNillableAnonymous sets the "anonymous" field if the given value is not nil.
func (qc *QuestionnaireCreate) SetNillableAnonymous(i *int) *QuestionnaireCreate {
	if i != nil {
		qc.SetAnonymous(*i)
	}
	return qc
}

// AddIncludeIDs adds the "include" edge to the Question entity by IDs.
func (qc *QuestionnaireCreate) AddIncludeIDs(ids ...int) *QuestionnaireCreate {
	qc.mutation.AddIncludeIDs(ids...)
	return qc
}

// AddInclude adds the "include" edges to the Question entity.
func (qc *QuestionnaireCreate) AddInclude(q ...*Question) *QuestionnaireCreate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return qc.AddIncludeIDs(ids...)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (qc *QuestionnaireCreate) SetCreatedByID(id int) *QuestionnaireCreate {
	qc.mutation.SetCreatedByID(id)
	return qc
}

// SetNillableCreatedByID sets the "created_by" edge to the User entity by ID if the given value is not nil.
func (qc *QuestionnaireCreate) SetNillableCreatedByID(id *int) *QuestionnaireCreate {
	if id != nil {
		qc = qc.SetCreatedByID(*id)
	}
	return qc
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (qc *QuestionnaireCreate) SetCreatedBy(u *User) *QuestionnaireCreate {
	return qc.SetCreatedByID(u.ID)
}

// Mutation returns the QuestionnaireMutation object of the builder.
func (qc *QuestionnaireCreate) Mutation() *QuestionnaireMutation {
	return qc.mutation
}

// Save creates the Questionnaire in the database.
func (qc *QuestionnaireCreate) Save(ctx context.Context) (*Questionnaire, error) {
	qc.defaults()
	return withHooks(ctx, qc.sqlSave, qc.mutation, qc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (qc *QuestionnaireCreate) SaveX(ctx context.Context) *Questionnaire {
	v, err := qc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qc *QuestionnaireCreate) Exec(ctx context.Context) error {
	_, err := qc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qc *QuestionnaireCreate) ExecX(ctx context.Context) {
	if err := qc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qc *QuestionnaireCreate) defaults() {
	if _, ok := qc.mutation.CreatedAt(); !ok {
		v := questionnaire.DefaultCreatedAt()
		qc.mutation.SetCreatedAt(v)
	}
	if _, ok := qc.mutation.UpdatedAt(); !ok {
		v := questionnaire.DefaultUpdatedAt()
		qc.mutation.SetUpdatedAt(v)
	}
	if _, ok := qc.mutation.Anonymous(); !ok {
		v := questionnaire.DefaultAnonymous
		qc.mutation.SetAnonymous(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qc *QuestionnaireCreate) check() error {
	if _, ok := qc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Questionnaire.created_at"`)}
	}
	if _, ok := qc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Questionnaire.updated_at"`)}
	}
	if _, ok := qc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Questionnaire.name"`)}
	}
	if _, ok := qc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Questionnaire.description"`)}
	}
	if _, ok := qc.mutation.Object(); !ok {
		return &ValidationError{Name: "object", err: errors.New(`ent: missing required field "Questionnaire.object"`)}
	}
	if _, ok := qc.mutation.Anonymous(); !ok {
		return &ValidationError{Name: "anonymous", err: errors.New(`ent: missing required field "Questionnaire.anonymous"`)}
	}
	return nil
}

func (qc *QuestionnaireCreate) sqlSave(ctx context.Context) (*Questionnaire, error) {
	if err := qc.check(); err != nil {
		return nil, err
	}
	_node, _spec := qc.createSpec()
	if err := sqlgraph.CreateNode(ctx, qc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	qc.mutation.id = &_node.ID
	qc.mutation.done = true
	return _node, nil
}

func (qc *QuestionnaireCreate) createSpec() (*Questionnaire, *sqlgraph.CreateSpec) {
	var (
		_node = &Questionnaire{config: qc.config}
		_spec = sqlgraph.NewCreateSpec(questionnaire.Table, sqlgraph.NewFieldSpec(questionnaire.FieldID, field.TypeInt))
	)
	if value, ok := qc.mutation.CreatedAt(); ok {
		_spec.SetField(questionnaire.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := qc.mutation.UpdatedAt(); ok {
		_spec.SetField(questionnaire.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := qc.mutation.Name(); ok {
		_spec.SetField(questionnaire.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := qc.mutation.Description(); ok {
		_spec.SetField(questionnaire.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := qc.mutation.Object(); ok {
		_spec.SetField(questionnaire.FieldObject, field.TypeString, value)
		_node.Object = value
	}
	if value, ok := qc.mutation.Anonymous(); ok {
		_spec.SetField(questionnaire.FieldAnonymous, field.TypeInt, value)
		_node.Anonymous = value
	}
	if nodes := qc.mutation.IncludeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   questionnaire.IncludeTable,
			Columns: questionnaire.IncludePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := qc.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questionnaire.CreatedByTable,
			Columns: []string{questionnaire.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_create = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuestionnaireCreateBulk is the builder for creating many Questionnaire entities in bulk.
type QuestionnaireCreateBulk struct {
	config
	err      error
	builders []*QuestionnaireCreate
}

// Save creates the Questionnaire entities in the database.
func (qcb *QuestionnaireCreateBulk) Save(ctx context.Context) ([]*Questionnaire, error) {
	if qcb.err != nil {
		return nil, qcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(qcb.builders))
	nodes := make([]*Questionnaire, len(qcb.builders))
	mutators := make([]Mutator, len(qcb.builders))
	for i := range qcb.builders {
		func(i int, root context.Context) {
			builder := qcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuestionnaireMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, qcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, qcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, qcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (qcb *QuestionnaireCreateBulk) SaveX(ctx context.Context) []*Questionnaire {
	v, err := qcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qcb *QuestionnaireCreateBulk) Exec(ctx context.Context) error {
	_, err := qcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qcb *QuestionnaireCreateBulk) ExecX(ctx context.Context) {
	if err := qcb.Exec(ctx); err != nil {
		panic(err)
	}
}
