// Code generated by ent, DO NOT EDIT.

package ent

import (
	"questionnaire/ent/answer"
	"questionnaire/ent/question"
	"questionnaire/ent/questionnaire"
	"questionnaire/ent/schema"
	"questionnaire/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	answerMixin := schema.Answer{}.Mixin()
	answerMixinFields0 := answerMixin[0].Fields()
	_ = answerMixinFields0
	answerFields := schema.Answer{}.Fields()
	_ = answerFields
	// answerDescCreatedAt is the schema descriptor for created_at field.
	answerDescCreatedAt := answerMixinFields0[0].Descriptor()
	// answer.DefaultCreatedAt holds the default value on creation for the created_at field.
	answer.DefaultCreatedAt = answerDescCreatedAt.Default.(func() time.Time)
	// answerDescUpdatedAt is the schema descriptor for updated_at field.
	answerDescUpdatedAt := answerMixinFields0[1].Descriptor()
	// answer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	answer.DefaultUpdatedAt = answerDescUpdatedAt.Default.(func() time.Time)
	// answer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	answer.UpdateDefaultUpdatedAt = answerDescUpdatedAt.UpdateDefault.(func() time.Time)
	questionMixin := schema.Question{}.Mixin()
	questionMixinFields0 := questionMixin[0].Fields()
	_ = questionMixinFields0
	questionFields := schema.Question{}.Fields()
	_ = questionFields
	// questionDescCreatedAt is the schema descriptor for created_at field.
	questionDescCreatedAt := questionMixinFields0[0].Descriptor()
	// question.DefaultCreatedAt holds the default value on creation for the created_at field.
	question.DefaultCreatedAt = questionDescCreatedAt.Default.(func() time.Time)
	// questionDescUpdatedAt is the schema descriptor for updated_at field.
	questionDescUpdatedAt := questionMixinFields0[1].Descriptor()
	// question.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	question.DefaultUpdatedAt = questionDescUpdatedAt.Default.(func() time.Time)
	// question.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	question.UpdateDefaultUpdatedAt = questionDescUpdatedAt.UpdateDefault.(func() time.Time)
	questionnaireMixin := schema.Questionnaire{}.Mixin()
	questionnaireMixinFields0 := questionnaireMixin[0].Fields()
	_ = questionnaireMixinFields0
	questionnaireFields := schema.Questionnaire{}.Fields()
	_ = questionnaireFields
	// questionnaireDescCreatedAt is the schema descriptor for created_at field.
	questionnaireDescCreatedAt := questionnaireMixinFields0[0].Descriptor()
	// questionnaire.DefaultCreatedAt holds the default value on creation for the created_at field.
	questionnaire.DefaultCreatedAt = questionnaireDescCreatedAt.Default.(func() time.Time)
	// questionnaireDescUpdatedAt is the schema descriptor for updated_at field.
	questionnaireDescUpdatedAt := questionnaireMixinFields0[1].Descriptor()
	// questionnaire.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	questionnaire.DefaultUpdatedAt = questionnaireDescUpdatedAt.Default.(func() time.Time)
	// questionnaire.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	questionnaire.UpdateDefaultUpdatedAt = questionnaireDescUpdatedAt.UpdateDefault.(func() time.Time)
	// questionnaireDescAnonymous is the schema descriptor for anonymous field.
	questionnaireDescAnonymous := questionnaireFields[3].Descriptor()
	// questionnaire.DefaultAnonymous holds the default value on creation for the anonymous field.
	questionnaire.DefaultAnonymous = questionnaireDescAnonymous.Default.(int)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescGender is the schema descriptor for gender field.
	userDescGender := userFields[1].Descriptor()
	// user.DefaultGender holds the default value on creation for the gender field.
	user.DefaultGender = userDescGender.Default.(int)
	// userDescUserType is the schema descriptor for user_type field.
	userDescUserType := userFields[3].Descriptor()
	// user.DefaultUserType holds the default value on creation for the user_type field.
	user.DefaultUserType = userDescUserType.Default.(int)
}
