// Code generated by ent, DO NOT EDIT.

package questionnaire

import (
	"questionnaire/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldDescription, v))
}

// Object applies equality check predicate on the "object" field. It's identical to ObjectEQ.
func Object(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldObject, v))
}

// Anonymous applies equality check predicate on the "anonymous" field. It's identical to AnonymousEQ.
func Anonymous(v int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldAnonymous, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldContainsFold(FieldDescription, v))
}

// ObjectEQ applies the EQ predicate on the "object" field.
func ObjectEQ(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldObject, v))
}

// ObjectNEQ applies the NEQ predicate on the "object" field.
func ObjectNEQ(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNEQ(FieldObject, v))
}

// ObjectIn applies the In predicate on the "object" field.
func ObjectIn(vs ...string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldIn(FieldObject, vs...))
}

// ObjectNotIn applies the NotIn predicate on the "object" field.
func ObjectNotIn(vs ...string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNotIn(FieldObject, vs...))
}

// ObjectGT applies the GT predicate on the "object" field.
func ObjectGT(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGT(FieldObject, v))
}

// ObjectGTE applies the GTE predicate on the "object" field.
func ObjectGTE(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGTE(FieldObject, v))
}

// ObjectLT applies the LT predicate on the "object" field.
func ObjectLT(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLT(FieldObject, v))
}

// ObjectLTE applies the LTE predicate on the "object" field.
func ObjectLTE(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLTE(FieldObject, v))
}

// ObjectContains applies the Contains predicate on the "object" field.
func ObjectContains(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldContains(FieldObject, v))
}

// ObjectHasPrefix applies the HasPrefix predicate on the "object" field.
func ObjectHasPrefix(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldHasPrefix(FieldObject, v))
}

// ObjectHasSuffix applies the HasSuffix predicate on the "object" field.
func ObjectHasSuffix(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldHasSuffix(FieldObject, v))
}

// ObjectEqualFold applies the EqualFold predicate on the "object" field.
func ObjectEqualFold(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEqualFold(FieldObject, v))
}

// ObjectContainsFold applies the ContainsFold predicate on the "object" field.
func ObjectContainsFold(v string) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldContainsFold(FieldObject, v))
}

// AnonymousEQ applies the EQ predicate on the "anonymous" field.
func AnonymousEQ(v int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldEQ(FieldAnonymous, v))
}

// AnonymousNEQ applies the NEQ predicate on the "anonymous" field.
func AnonymousNEQ(v int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNEQ(FieldAnonymous, v))
}

// AnonymousIn applies the In predicate on the "anonymous" field.
func AnonymousIn(vs ...int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldIn(FieldAnonymous, vs...))
}

// AnonymousNotIn applies the NotIn predicate on the "anonymous" field.
func AnonymousNotIn(vs ...int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldNotIn(FieldAnonymous, vs...))
}

// AnonymousGT applies the GT predicate on the "anonymous" field.
func AnonymousGT(v int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGT(FieldAnonymous, v))
}

// AnonymousGTE applies the GTE predicate on the "anonymous" field.
func AnonymousGTE(v int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldGTE(FieldAnonymous, v))
}

// AnonymousLT applies the LT predicate on the "anonymous" field.
func AnonymousLT(v int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLT(FieldAnonymous, v))
}

// AnonymousLTE applies the LTE predicate on the "anonymous" field.
func AnonymousLTE(v int) predicate.Questionnaire {
	return predicate.Questionnaire(sql.FieldLTE(FieldAnonymous, v))
}

// HasInclude applies the HasEdge predicate on the "include" edge.
func HasInclude() predicate.Questionnaire {
	return predicate.Questionnaire(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, IncludeTable, IncludePrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIncludeWith applies the HasEdge predicate on the "include" edge with a given conditions (other predicates).
func HasIncludeWith(preds ...predicate.Question) predicate.Questionnaire {
	return predicate.Questionnaire(func(s *sql.Selector) {
		step := newIncludeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreatedBy applies the HasEdge predicate on the "created_by" edge.
func HasCreatedBy() predicate.Questionnaire {
	return predicate.Questionnaire(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatedByTable, CreatedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedByWith applies the HasEdge predicate on the "created_by" edge with a given conditions (other predicates).
func HasCreatedByWith(preds ...predicate.User) predicate.Questionnaire {
	return predicate.Questionnaire(func(s *sql.Selector) {
		step := newCreatedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Questionnaire) predicate.Questionnaire {
	return predicate.Questionnaire(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Questionnaire) predicate.Questionnaire {
	return predicate.Questionnaire(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Questionnaire) predicate.Questionnaire {
	return predicate.Questionnaire(sql.NotPredicates(p))
}
